import numpy as np

parameters_3_global = {

        'k_H' : 3,
        'dH' : 0.05,
        'theta_N' : 100_000,
        'theta_K' : 50_000,
        'tau_Q' : 1,
        'tau_U' : 1,
        'd_SCSF' : 0.3,
        'd_S' : 0.1,
        'd_Q' : 0.95,
        'd_U' : 0.5,
        'd_P' : 0.95,
        'd_A' : 0.95,
        'g_N' : 0.10,
        'N_oo' : 2 * 10**7,
        'N_half' : 2500,
        'S_PH' : 2,
        'S_PS' : 5,
        'S_PQ' : 10,
        'S_AU' : 15,
        'S_AH' : 0,
        'S_AS' : 0,
        'S_AM' : 8,
        'S_SCSF' : 5000,
        'S_KD' : 1,
        'k_sn' : 3,
        'k_nq' : 10,
        'k_nm' : 3,
        'k_ns' : 0.5,
        'R_KU' : 10,
        'I_crit' : 0.8,
        'K_crit' : 20_000,
        'k' : 1,
        'psi' : 1,
        'd_M' : 9/10,
        'd_MF' : 0.3,
        'S_KMD' : 1/5,
        'S_KQ' : 1/3,
        'C_QM' : 1,
        'C_MDM' : 1,
        'C_UM' : 1/3,
        'S_MF' : 1000,
        'omega' : 0.6,
        'C_UP' : 2,
        'alpha': 1/3,
        'gamma' : 0.0005,  
        'delta' : 0.2,
        'H_crit' : 0.4,
        'beta_N' :  10**-3          

    }

parameters_3_global_bk = {

        'k_H' : 3,
        'dH' : 0.05,
        'theta_N' : 100_000,
        'theta_K' : 50_000,
        'tau_Q' : 1,
        'tau_U' : 1,
        'd_SCSF' : 0.3,
        'd_S' : 0.1,
        'd_Q' : 0.95,
        'd_U' : 0.5,
        'd_P' : 0.95,
        'd_A' : 0.95,
        'g_N' : 0.10,
        'N_oo' : 2 * 10**7,
        'N_half' : 2500,
        'S_PH' : 2,
        'S_PS' : 5,
        'S_PQ' : 10,
        'S_AU' : 15,
        'S_AH' : 0,
        'S_AS' : 0,
        'S_AM' : 8,
        'S_SCSF' : 5000,
        'S_KD' : 1,
        'k_sn' : 3,
        'k_nq' : 10,
        'k_nm' : 3,
        'k_ns' : 0.5,
        'R_KU' : 10,
        'I_crit' : 0.8,
        'K_crit' : 20_000,
        'k' : 1,
        'psi' : 1,
        'd_M' : 9/10,
        'd_MF' : 0.3,
        'S_KMD' : 1/5,
        'S_KQ' : 1/3,
        'C_QM' : 1,
        'C_MDM' : 1,
        'C_UM' : 1/3,
        'S_MF' : 1000,
        'omega' : 0.6,
        'C_UP' : 2,
        'alpha': 1/3,
        'gamma' : 0.0005,  
        'delta' : 0.2,
        'H_crit' : 0.4,
        'beta_N' :  10**-3   

    }

key_names_3 = [
    'k_H',
    'dH',
    'theta_N',
    'theta_K',
    'tau_Q',
    'tau_U',
    'd_SCSF',
    'd_S',
    'd_Q',
    'd_U',
    'd_P',
    'd_A',
    'g_N',
    'N_oo',
    'N_half',
    'S_PH',
    'S_PS',
    'S_PQ',
    'S_AU',
    'S_AH',
    'S_AS',
    'S_AM',
    'S_SCSF',
    'S_KD',
    'k_sn',
    'k_nq',
    'k_nm',
    'k_ns',
    'R_KU',
    'I_crit',
    'K_crit',
    'k',
    'psi',
    'd_M',
    'd_MF',
    'S_KMD',
    'S_KQ',
    'C_QM',
    'C_MDM',
    'C_UM',
    'S_MF',
    'omega',
    'C_UP',
    'alpha',
    'gamma', 
    'delta',
    'H_crit',
    'beta_N'
]